-- XpelBeauty NG — Stockists import (LIST JULY)
-- Replaces ALL rows in `stores`. Import once in phpMyAdmin.
-- 605 stores (27 INDIVIDUAL rows excluded)

SET NAMES utf8mb4;
DELETE FROM `stores`;

INSERT INTO `stores` (`name`, `city`, `state`) VALUES
('Market Square Aba', 'Aba', 'Abia'),
('Market square Aba 2', 'Aba', 'Abia'),
('Jovit Mart, Umuahia', 'Umuahia', 'Abia'),
('Market Square Umuahia', 'Umuahia', 'Abia'),
('247 Supermarket, Uyo', 'Uyo', 'Akwa Ibom'),
('All time Supermarket 3, Uyo', 'Uyo', 'Akwa Ibom'),
('All Time Supermarket, Uyo', 'Uyo', 'Akwa Ibom'),
('Christ the King Supermarket Uyo', 'Uyo', 'Akwa Ibom'),
('De Samic, Uyo', 'Uyo', 'Akwa Ibom'),
('Down Town Shopping Complex, Uyo', 'Uyo', 'Akwa Ibom'),
('Efg Mart Supermarket, Uyo 1', 'Uyo', 'Akwa Ibom'),
('Efg Mart Uyo', 'Uyo', 'Akwa Ibom'),
('Hangers Supermarket, Uyo', 'Uyo', 'Akwa Ibom'),
('Jane & Juliet Uyo', 'Uyo', 'Akwa Ibom'),
('Judel Supermarket', 'Uyo', 'Akwa Ibom'),
('Market Square Ikot Epene', 'Uyo', 'Akwa Ibom'),
('Market Square Uyo', 'Uyo', 'Akwa Ibom'),
('Nteps Supermarket Uyo', 'Uyo', 'Akwa Ibom'),
('Rich Way Supermarket Uyo', 'Uyo', 'Akwa Ibom'),
('Value Plus Supermarket Uyo', 'Uyo', 'Akwa Ibom'),
('Everyday Supermarket Awka E12', 'Awka', 'Anambra'),
('Market Square Awka', 'Awka', 'Anambra'),
('Radopin Supermarket 1 Ziks Avenue Awka', 'Awka', 'Anambra'),
('Radopin Supermarket 2 Aroma Junction Awka', 'Awka', 'Anambra'),
('Radopin Supermarket 3 Kwata Junction Awka', 'Awka', 'Anambra'),
('Zara Stores, Awka', 'Awka', 'Anambra'),
('Obinna Onitsha', 'Onitsha', 'Anambra'),
('Paxs Pharmacy Onitsha', 'Onitsha', 'Anambra'),
('Shoprite Sr Onitsha mall 64769', 'Onitsha', 'Anambra'),
('Zara Stores, Onitsha', 'Onitsha', 'Anambra'),
('Assorted Super Centre, Yenogoa', 'Yenagoa', 'Bayelsa'),
('De Royal Mall, Yenogoa', 'Yenagoa', 'Bayelsa'),
('General Supermarket Yenogoa', 'Yenagoa', 'Bayelsa'),
('Joepal Supermarket Yenogoa', 'Yenagoa', 'Bayelsa'),
('Lozzy Supermarket Yenogua', 'Yenagoa', 'Bayelsa'),
('Market Square Yenogoa', 'Yenagoa', 'Bayelsa'),
('Oasis Mart, Yenogoa', 'Yenagoa', 'Bayelsa'),
('Sureplus Supermarket Yenogoa', 'Yenagoa', 'Bayelsa'),
('Market Square Gsm Market Maiduguri, Borno', 'Maiduguri', 'Borno'),
('Enumex Cosmetics Calabar', 'Calabar', 'Cross River'),
('Spar Calabar Mall, Calabar', 'Calabar', 'Cross River'),
('Safari Hypermarket, Warri', '', 'Delta'),
('Amaka Stores, Asaba', 'Asaba', 'Delta'),
('Annies Market Place, Asaba', 'Asaba', 'Delta'),
('Centrus Mall, Asaba', 'Asaba', 'Delta'),
('Corner Mart, Asaba', 'Asaba', 'Delta'),
('Everyday Supermarket Summit Asaba E10', 'Asaba', 'Delta'),
('Market Square Asaba', 'Asaba', 'Delta'),
('Market Square Asaba Mall, Okpanam Road', 'Asaba', 'Delta'),
('Pukka Supermarket, Asaba', 'Asaba', 'Delta'),
('Shoprite Sr Asaba 85923', 'Asaba', 'Delta'),
('Townsquare Asaba', 'Asaba', 'Delta'),
('Everyday Supermarket Abakaliki E13', 'Abakaliki', 'Ebonyi'),
('Alpha Pet, Benin', 'Benin City', 'Edo'),
('Amambraco Supermarket, Benin', 'Benin City', 'Edo'),
('Awari Supermarket, Benin', 'Benin City', 'Edo'),
('Coka Pharmacy & Stores, Benin', 'Benin City', 'Edo'),
('Coka Pharmacy & Stores, Off Sapele RD', 'Benin City', 'Edo'),
('Elixir Supermarket Benin', 'Benin City', 'Edo'),
('Enascolin Ventures, Benin', 'Benin City', 'Edo'),
('Ford Mart Benin City', 'Benin City', 'Edo'),
('Ford Mart Supermarket Adolor, Benin City', 'Benin City', 'Edo'),
('Ford Mart Supermarket Supermarket, Isikolor Road, Benin City', 'Benin City', 'Edo'),
('GPS Shopping Mall, Benin', 'Benin City', 'Edo'),
('Hexcel Supermarket, Benin City', 'Benin City', 'Edo'),
('IK Pharmacy and Supermarket, Benin', 'Benin City', 'Edo'),
('Jara Benin', 'Benin City', 'Edo'),
('Jara Edlp Benin', 'Benin City', 'Edo'),
('Kevs Departmental Stores, Benin', 'Benin City', 'Edo'),
('LMSN Supermarket, Benin', 'Benin City', 'Edo'),
('Mankind Pharmacy and Supermarket, Benin', 'Benin City', 'Edo'),
('Market Square Aduwawa Benin 2', 'Benin City', 'Edo'),
('Market Square Airport Road, Benin 3', 'Benin City', 'Edo'),
('Market Square Benin Sapele Road', 'Benin City', 'Edo'),
('MM2 Ekosodine, Benin', 'Benin City', 'Edo'),
('MM2 Isihor, Benin', 'Benin City', 'Edo'),
('Nick supermarket, Benin', 'Benin City', 'Edo'),
('Phil Hallmark Benin', 'Benin City', 'Edo'),
('Phil Hallmark Benin 2', 'Benin City', 'Edo'),
('Prime Mart By Morzi', 'Benin City', 'Edo'),
('Real Care Pharmacy and Supermarket, Benin', 'Benin City', 'Edo'),
('Shoprite Benin Mall', 'Benin City', 'Edo'),
('Stop 2 Shop Benin', 'Benin City', 'Edo'),
('Vintage Supermarket, Benin', 'Benin City', 'Edo'),
('Wonder Supermarket, Benin', 'Benin City', 'Edo'),
('Ceci Supermarket, Ado-Ekiti', 'Ado-Ekiti', 'Ekiti'),
('Jara Ekiti', 'Ado-Ekiti', 'Ekiti'),
('Nao Supermarket, Ado Ekiti', 'Ado-Ekiti', 'Ekiti'),
('Staleg Mall, Ado-Ekiti', 'Ado-Ekiti', 'Ekiti'),
('Best Choice Enugu', 'Enugu', 'Enugu'),
('Freshshop Supermarket Transekulu, Enugu', 'Enugu', 'Enugu'),
('Market Square Enugu', 'Enugu', 'Enugu'),
('Marvel Nissi Store', 'Enugu', 'Enugu'),
('Roban Stores Enugu', 'Enugu', 'Enugu'),
('Shopper Gate Enugu', 'Enugu', 'Enugu'),
('Shoprite SR Enugu 56247', 'Enugu', 'Enugu'),
('Spar Enugu Mall', 'Enugu', 'Enugu'),
('2k Supermarket, Abuja', 'Abuja', 'FCT Abuja'),
('Arinze, Wuse Abuja', 'Abuja', 'FCT Abuja'),
('Azores Supermarket Kuje, Abuja', 'Abuja', 'FCT Abuja'),
('Babbo Supermarket, Abuja', 'Abuja', 'FCT Abuja'),
('Best Buy Supermarket, Kuje', 'Abuja', 'FCT Abuja'),
('Bless Shop Supermarket, Abuja', 'Abuja', 'FCT Abuja'),
('Blessed Victoria Supermarket, Abuja', 'Abuja', 'FCT Abuja'),
('Bright Cosmetics, Abuja', 'Abuja', 'FCT Abuja'),
('Callys Venture Beauty Store, Wuse Market', 'Abuja', 'FCT Abuja'),
('CH Cosmetics Wuse Market, Abuja', 'Abuja', 'FCT Abuja'),
('Chidivac Pharmacy & Stores, Abuja', 'Abuja', 'FCT Abuja'),
('Chimex Stores, Wuse Market', 'Abuja', 'FCT Abuja'),
('China sky supermarket, Abuja', 'Abuja', 'FCT Abuja'),
('Cost Cutters SUpermarket Abuja', 'Abuja', 'FCT Abuja'),
('CyMarc International Limited, Wuse Abuja', 'Abuja', 'FCT Abuja'),
('De petex Cosmetics, Abuja', 'Abuja', 'FCT Abuja'),
('DFD Pharmacy & Superstore, Lugbe', 'Abuja', 'FCT Abuja'),
('Eagle Success cosmetics, Abuja', 'Abuja', 'FCT Abuja'),
('Ebeano Supermarket Abuja', 'Abuja', 'FCT Abuja'),
('Eden Cosmetics Wuse Market, Abuja', 'Abuja', 'FCT Abuja'),
('El- Roi super stores, Auja', 'Abuja', 'FCT Abuja'),
('Family Wellness Abuja', 'Abuja', 'FCT Abuja'),
('Faxx Stores & Trading Ltd, Abuja', 'Abuja', 'FCT Abuja'),
('Goshen Stores, Abuja', 'Abuja', 'FCT Abuja'),
('Grand Product Abuja', 'Abuja', 'FCT Abuja'),
('H-medix Abuja', 'Abuja', 'FCT Abuja'),
('I C World Supermarket Gwarinpa, Abuja', 'Abuja', 'FCT Abuja'),
('IK P supermarket, Abuja', 'Abuja', 'FCT Abuja'),
('James Beauty Cosmetics, Abuja', 'Abuja', 'FCT Abuja'),
('Lead Gate Supermarket Jabi Lake, Abuja', 'Abuja', 'FCT Abuja'),
('Market Square Apo 2 Mall, Apo Round About, Abuja', 'Abuja', 'FCT Abuja'),
('Market Square Dawaki District, Abuja', 'Abuja', 'FCT Abuja'),
('Market Square Gateway Mall, Abuja', 'Abuja', 'FCT Abuja'),
('Market Square Gwarinpa Abuja', 'Abuja', 'FCT Abuja'),
('Market Square Karu, Abuja', 'Abuja', 'FCT Abuja'),
('Market Square Kuje, Abuja', 'Abuja', 'FCT Abuja'),
('Mesdon Int''l Ltd, Abuja', 'Abuja', 'FCT Abuja'),
('Mostel Cosmetics, Abuja', 'Abuja', 'FCT Abuja'),
('Mr. ugoo ABJ', 'Abuja', 'FCT Abuja'),
('Multimac cosmetic store, Abuja', 'Abuja', 'FCT Abuja'),
('ND Stores, Kuje', 'Abuja', 'FCT Abuja'),
('Oliva Twist Supermarket, Abuja', 'Abuja', 'FCT Abuja'),
('Onyeze Cosmetics, Abuja', 'Abuja', 'FCT Abuja'),
('Open Door Supermarket Wuse', 'Abuja', 'FCT Abuja'),
('Organic beauty cosmetics, Abuja', 'Abuja', 'FCT Abuja'),
('Prince Ebeano Abuja', 'Abuja', 'FCT Abuja'),
('Prince Ebeano Supermarket, Gudu Abuja', 'Abuja', 'FCT Abuja'),
('Sahad Cosmetics Abuja', 'Abuja', 'FCT Abuja'),
('Shoprite Sr Abuja Gateway 96663', 'Abuja', 'FCT Abuja'),
('Spar Central Business District, Abuja', 'Abuja', 'FCT Abuja'),
('Spar Gwarinpa, Abuja', 'Abuja', 'FCT Abuja'),
('Spar Wuse II, Abuja', 'Abuja', 'FCT Abuja'),
('Spar Wuse Zone 5, Abuja', 'Abuja', 'FCT Abuja'),
('Tobeklen Pharmacy & Stores, Abuja', 'Abuja', 'FCT Abuja'),
('Top Outlet Stores, Abuja', 'Abuja', 'FCT Abuja'),
('Tosco Cosmetics Wuse Martket', 'Abuja', 'FCT Abuja'),
('Trolley Supermarket Wuse II, Abuja', 'Abuja', 'FCT Abuja'),
('AT Cosmetics, Owerri', 'Owerri', 'Imo'),
('Destiny Supermarket Owerri', 'Owerri', 'Imo'),
('Everyday Supermarket 4040 Owerri E11', 'Owerri', 'Imo'),
('Everyday Supermarket Ikenegbu Owerri E4', 'Owerri', 'Imo'),
('Everyday Supermarket Imsu Owerri E8', 'Owerri', 'Imo'),
('Everyday Supermarket Mcc Owerri E7', 'Owerri', 'Imo'),
('Everyday Supermarket World Bank Owerri E5', 'Owerri', 'Imo'),
('Family Mart', 'Owerri', 'Imo'),
('Gain More Supermarket', 'Owerri', 'Imo'),
('Glorisco Supermarket Owerri', 'Owerri', 'Imo'),
('Leedel Super Store', 'Owerri', 'Imo'),
('Leedel Superstore Ikenegbu, Owerri', 'Owerri', 'Imo'),
('Lython Cosmetics Ekeonuwa, Owerri', 'Owerri', 'Imo'),
('Market Square Owerri', 'Owerri', 'Imo'),
('Market Square Owerri Mall', 'Owerri', 'Imo'),
('Priceless Stores Okigwe Rd, Owerri', 'Owerri', 'Imo'),
('Priceless Stores Orlu Raod, Owerri', 'Owerri', 'Imo'),
('Priceless Stores Youth center layout, Owerri', 'Owerri', 'Imo'),
('Promall, Owerri', 'Owerri', 'Imo'),
('Save More Market Place', 'Owerri', 'Imo'),
('shoprite owerri', 'Owerri', 'Imo'),
('Market Square Kaduna', 'Kaduna', 'Kaduna'),
('Shoprite Sr Kaduna Mall 9663', 'Kaduna', 'Kaduna'),
('Grand Products Kano', 'Kano', 'Kano'),
('Ify Fabulous Cosmetics, Ilorin', 'Ilorin', 'Kwara'),
('SIsters Lounge, Ilorin', 'Ilorin', 'Kwara'),
('Adivia Stores, Lekki County Home', 'Lagos Island / Lekki', 'Lagos'),
('Bag It supermarket Admiralty Way, Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Better Mart Badore', 'Lagos Island / Lekki', 'Lagos'),
('Blenco Addo', 'Lagos Island / Lekki', 'Lagos'),
('Blenco Ilasan Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Blenco Supermarket Ajiwe, Ajah', 'Lagos Island / Lekki', 'Lagos'),
('Blenco Supermarket, Eputu ibeju Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Blenco Supermarket, Sangotedo', 'Lagos Island / Lekki', 'Lagos'),
('Careforte Pharm VI', 'Lagos Island / Lekki', 'Lagos'),
('CEC Drug n more pharmacy and beauty, Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Ceo''s Mart', 'Lagos Island / Lekki', 'Lagos'),
('Compra Mart', 'Lagos Island / Lekki', 'Lagos'),
('Compra Mart, Orchid', 'Lagos Island / Lekki', 'Lagos'),
('Day Toner People''s Pharmacy, Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Daytoner Aja', 'Lagos Island / Lekki', 'Lagos'),
('Delis VI', 'Lagos Island / Lekki', 'Lagos'),
('Delux Supermarket Sangotedo', 'Lagos Island / Lekki', 'Lagos'),
('Ebeano Supermarket Agungi Branch', 'Lagos Island / Lekki', 'Lagos'),
('Ebeano Supermarket Chevron Branch', 'Lagos Island / Lekki', 'Lagos'),
('Ebeano Supermarket Eleganza', 'Lagos Island / Lekki', 'Lagos'),
('Ebeano Supermarket Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Ebeano SUpermarket Oniru', 'Lagos Island / Lekki', 'Lagos'),
('Ebeano Supermarket, Jakande', 'Lagos Island / Lekki', 'Lagos'),
('Enej Supermarket, Orchid Rd', 'Lagos Island / Lekki', 'Lagos'),
('Ever Bright Store', 'Lagos Island / Lekki', 'Lagos'),
('Feebees Retail Services, Oniru', 'Lagos Island / Lekki', 'Lagos'),
('Foodco Ikoyi', 'Lagos Island / Lekki', 'Lagos'),
('Foodco Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Freedom Mart Supermarket, Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Grand Products VI', 'Lagos Island / Lekki', 'Lagos'),
('Greeneil Supermarket Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Greeneil Supermarket Osapa London', 'Lagos Island / Lekki', 'Lagos'),
('Hartley Supermarket Ikoyi', 'Lagos Island / Lekki', 'Lagos'),
('Hartleys Supermarket VI', 'Lagos Island / Lekki', 'Lagos'),
('Jendol Super Store, Ajah Lagos', 'Lagos Island / Lekki', 'Lagos'),
('Justrite Superstore Ikate Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Kls supermarket, Ikeja', 'Lagos Island / Lekki', 'Lagos'),
('Lapas Mall Ajah', 'Lagos Island / Lekki', 'Lagos'),
('Lapaz Mall Limited', 'Lagos Island / Lekki', 'Lagos'),
('Limitless Mart, Eputu', 'Lagos Island / Lekki', 'Lagos'),
('Market Square Lekki, Lagos', 'Lagos Island / Lekki', 'Lagos'),
('Market Square Sangotedo, Lagos', 'Lagos Island / Lekki', 'Lagos'),
('Max Ambi supermarket, Ibeju Lekki', 'Lagos Island / Lekki', 'Lagos'),
('MC Awesome Supermarket, Ajah', 'Lagos Island / Lekki', 'Lagos'),
('Medplus Pharm', 'Lagos Island / Lekki', 'Lagos'),
('Mega Plaza', 'Lagos Island / Lekki', 'Lagos'),
('Mega Plaza VI', 'Lagos Island / Lekki', 'Lagos'),
('Mitch & Good Supermarket, Ikoyi', 'Lagos Island / Lekki', 'Lagos'),
('Mopheth Pharmacy, Vi', 'Lagos Island / Lekki', 'Lagos'),
('Multikers Supermarket VI', 'Lagos Island / Lekki', 'Lagos'),
('My Groceries 2go', 'Lagos Island / Lekki', 'Lagos'),
('My Mart, Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Naija Medix Pharmacy, Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Okoli Supermarket Ikoyi', 'Lagos Island / Lekki', 'Lagos'),
('Ozzy Stores Eti Osa', 'Lagos Island / Lekki', 'Lagos'),
('Ozzy Stores Ilaje', 'Lagos Island / Lekki', 'Lagos'),
('Ozzy Stores Osapa London', 'Lagos Island / Lekki', 'Lagos'),
('Palais de beaute cosmetics', 'Lagos Island / Lekki', 'Lagos'),
('Palais De Beaute Cosmetics, Big Shop', 'Lagos Island / Lekki', 'Lagos'),
('Palais De Beaute Cosmetics, Shop 1', 'Lagos Island / Lekki', 'Lagos'),
('Palais De Beaute Cosmetics, Shop 2', 'Lagos Island / Lekki', 'Lagos'),
('Palais De Beaute Cosmetics, Shop 3', 'Lagos Island / Lekki', 'Lagos'),
('Phylmart, Agungi', 'Lagos Island / Lekki', 'Lagos'),
('Pick n Pay Glover', 'Lagos Island / Lekki', 'Lagos'),
('Pick N Pay Vi', 'Lagos Island / Lekki', 'Lagos'),
('Quick Point Supermarket, Sangotedo', 'Lagos Island / Lekki', 'Lagos'),
('Replenish Supermarket Badore', 'Lagos Island / Lekki', 'Lagos'),
('Roinuj Supermarket, Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Shoprite SR Lekki Mall 64751', 'Lagos Island / Lekki', 'Lagos'),
('SkyMart', 'Lagos Island / Lekki', 'Lagos'),
('Sorfis Supermarket, Sangotedo', 'Lagos Island / Lekki', 'Lagos'),
('Spar Ikate Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Spinneys Supermarket Addo RD', 'Lagos Island / Lekki', 'Lagos'),
('St David Pharmacy Warehouse', 'Lagos Island / Lekki', 'Lagos'),
('SuperSaver Supermarket Lekki', 'Lagos Island / Lekki', 'Lagos'),
('Supersaver Supermarket, Lenox Mall Lekki', 'Lagos Island / Lekki', 'Lagos'),
('T & M Supermarket, Agungi', 'Lagos Island / Lekki', 'Lagos'),
('Temple Hill Ajah', 'Lagos Island / Lekki', 'Lagos'),
('Twins Faja Supermarket, Ajah', 'Lagos Island / Lekki', 'Lagos'),
('U B A Supermarket, Ogidan', 'Lagos Island / Lekki', 'Lagos'),
('U B A Supermarket, Orchid', 'Lagos Island / Lekki', 'Lagos'),
('Zetile Supermarket', 'Lagos Island / Lekki', 'Lagos'),
('3D Radiance Pharmacy, Gbagada', 'Lagos Mainland', 'Lagos'),
('6 to 9 Supermarket', 'Lagos Mainland', 'Lagos'),
('Alpha Pharmacy and Stores, Ikeja', 'Lagos Mainland', 'Lagos'),
('Bedrock Mart Bucknor Isolo', 'Lagos Mainland', 'Lagos'),
('Blenco Supermarket Abule Egba', 'Lagos Mainland', 'Lagos'),
('Blenco Supermarket Egbeda', 'Lagos Mainland', 'Lagos'),
('Blenco Supermarket, Amadiya', 'Lagos Mainland', 'Lagos'),
('D, Emperor Grand Mall', 'Lagos Mainland', 'Lagos'),
('DBANI Supermarket, Bariga', 'Lagos Mainland', 'Lagos'),
('Dee Kam Market Place, Ota', 'Lagos Mainland', 'Lagos'),
('Destiny Arikpo', 'Lagos Mainland', 'Lagos'),
('DFK Super Store, Palm Groove', 'Lagos Mainland', 'Lagos'),
('Edichart Shoping Mall', 'Lagos Mainland', 'Lagos'),
('Emmatos Super Store, Aboru', 'Lagos Mainland', 'Lagos'),
('Emmatos Super Store, Alagbado', 'Lagos Mainland', 'Lagos'),
('Emmatos Super Store, Ishashi 3', 'Lagos Mainland', 'Lagos'),
('Essentials by Grandview', 'Lagos Mainland', 'Lagos'),
('Et Al Farms Superstores, Ikeja', 'Lagos Mainland', 'Lagos'),
('Foodco Ikotun', 'Lagos Mainland', 'Lagos'),
('Globus Ago', 'Lagos Mainland', 'Lagos'),
('Globus supermarket Ajao Estate Lagos', 'Lagos Mainland', 'Lagos'),
('Go Trading Enterprises Apapa, Lagos', 'Lagos Mainland', 'Lagos'),
('Goodies Ikeja', 'Lagos Mainland', 'Lagos'),
('Grand Products Ikeja', 'Lagos Mainland', 'Lagos'),
('Healthrite Pharmacy 2', 'Lagos Mainland', 'Lagos'),
('Healthrite Pharmacy Randle', 'Lagos Mainland', 'Lagos'),
('Healthrite Pharmacy Tejuosho', 'Lagos Mainland', 'Lagos'),
('J Lush Supermarket, Ojota', 'Lagos Mainland', 'Lagos'),
('Jara Lagos', 'Lagos Mainland', 'Lagos'),
('Jendol Abule Egba', 'Lagos Mainland', 'Lagos'),
('Jendol Central Warehouse, Egbeda', 'Lagos Mainland', 'Lagos'),
('Jendol Odonguyan, Ikorodu', 'Lagos Mainland', 'Lagos'),
('Jendol Supermarket Alakuko', 'Lagos Mainland', 'Lagos'),
('Jendol Supermarket Igando 2', 'Lagos Mainland', 'Lagos'),
('Jendol Supermarket Ikorodu', 'Lagos Mainland', 'Lagos'),
('Jendol Supermarket Isheri', 'Lagos Mainland', 'Lagos'),
('Jendol SUpermarket Isolo', 'Lagos Mainland', 'Lagos'),
('Jendol Supermarket Ojodu', 'Lagos Mainland', 'Lagos'),
('Jendol Superstore Egbeda', 'Lagos Mainland', 'Lagos'),
('Jendol Superstore Oju Ore', 'Lagos Mainland', 'Lagos'),
('Jendol Superstores Ibafo', 'Lagos Mainland', 'Lagos'),
('Jendol Superstores Ijede, Ikorodu 3', 'Lagos Mainland', 'Lagos'),
('Jendol Superstores Magidun, Ikorodu 4', 'Lagos Mainland', 'Lagos'),
('Jendol Superstores, Ipaja', 'Lagos Mainland', 'Lagos'),
('Jendol Superstores, Onibukun', 'Lagos Mainland', 'Lagos'),
('Joeddy Supermarket, Anthony Village', 'Lagos Mainland', 'Lagos'),
('Justcom Stores, Ogudu', 'Lagos Mainland', 'Lagos'),
('Justrite Central Warehouse Ikeja', 'Lagos Mainland', 'Lagos'),
('Justrite Supermarktet Sango Otta', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Abule Egba', 'Lagos Mainland', 'Lagos'),
('Justrite SuperStore Akowonjo Egbeda', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Ayobo', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Casso, Lagos', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Dopemu', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Igando, Lagos State', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Iju', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Ikorodu', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Ikorodu 2', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Isolo', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Iyana Ipaja', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Odonguyan, Ikorodu 3', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Ojodu', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore Owode', 'Lagos Mainland', 'Lagos'),
('Justrite Superstore, Omole', 'Lagos Mainland', 'Lagos'),
('Justrite Superstores Alakuko', 'Lagos Mainland', 'Lagos'),
('Justrite Superstores Bariga', 'Lagos Mainland', 'Lagos'),
('Justrite Superstores Ekoro, Lagos', 'Lagos Mainland', 'Lagos'),
('Justrite Superstores Gowon Estate', 'Lagos Mainland', 'Lagos'),
('Justrite Superstores Ibafo Lagos', 'Lagos Mainland', 'Lagos'),
('Justrite Superstores, Ogba Ikeja', 'Lagos Mainland', 'Lagos'),
('Katta Supermarket', 'Lagos Mainland', 'Lagos'),
('Li-m Supermarket, Ota', 'Lagos Mainland', 'Lagos'),
('Macmannie Supermarket, Ogba', 'Lagos Mainland', 'Lagos'),
('Mama Tega, Tejuosho Market', 'Lagos Mainland', 'Lagos'),
('Market Square Festac', 'Lagos Mainland', 'Lagos'),
('Market square Maryland, Lagos', 'Lagos Mainland', 'Lagos'),
('Market Square Okota', 'Lagos Mainland', 'Lagos'),
('Market Square Owode Idiroko Road, Ogun State', 'Lagos Mainland', 'Lagos'),
('Market Square, Gbagada', 'Lagos Mainland', 'Lagos'),
('Maxland Shopping Center', 'Lagos Mainland', 'Lagos'),
('Mostan Super Stores, Gbagada', 'Lagos Mainland', 'Lagos'),
('Old English Abule Egba', 'Lagos Mainland', 'Lagos'),
('Old english Omole Phase', 'Lagos Mainland', 'Lagos'),
('Old English Stores GRA', 'Lagos Mainland', 'Lagos'),
('Old English Superstores, Ibadan', 'Lagos Mainland', 'Lagos'),
('Old English Surulere', 'Lagos Mainland', 'Lagos'),
('Omezera Supermarket, Ikeja', 'Lagos Mainland', 'Lagos'),
('One Source Mart, Ikeja', 'Lagos Mainland', 'Lagos'),
('Pay Day Supermarket Oworoshoki, Lagos', 'Lagos Mainland', 'Lagos'),
('Penafort Supermarket Festac', 'Lagos Mainland', 'Lagos'),
('Pharma Care Pharmacy, Festac', 'Lagos Mainland', 'Lagos'),
('Prestige Superstores Ajuwon, Akute', 'Lagos Mainland', 'Lagos'),
('Prestige Superstores Akesan, Igando', 'Lagos Mainland', 'Lagos'),
('Prestige Superstores Ishashi', 'Lagos Mainland', 'Lagos'),
('Prestige Superstores Iyana Paja', 'Lagos Mainland', 'Lagos'),
('Prime Mart Superstores Cement', 'Lagos Mainland', 'Lagos'),
('Prime Mart Superstores Ifo', 'Lagos Mainland', 'Lagos'),
('Prime Mart SuperStores Iyana Ishasgi RD Ojo, Lagos', 'Lagos Mainland', 'Lagos'),
('Prime Mart Superstores LASU Idimu IBa Rd AKesan Lagos', 'Lagos Mainland', 'Lagos'),
('Prime Mart Superstores Singer', 'Lagos Mainland', 'Lagos'),
('Prime Mart Superstores, Agbara', 'Lagos Mainland', 'Lagos'),
('Prime Mart Superstores, Okoko', 'Lagos Mainland', 'Lagos'),
('Prince Ebeano Supermarket Ikeja', 'Lagos Mainland', 'Lagos'),
('Q Mart Supermarket, Bariga', 'Lagos Mainland', 'Lagos'),
('Qwik Supermarket, Anthony', 'Lagos Mainland', 'Lagos'),
('Reno Supermarket Iyana School B/S 3', 'Lagos Mainland', 'Lagos'),
('Reno Supermarket, Ejigbo 2', 'Lagos Mainland', 'Lagos'),
('Reno Supermarket, Ikotun', 'Lagos Mainland', 'Lagos'),
('Reno Supermarket, Isheri 4', 'Lagos Mainland', 'Lagos'),
('Reno Superstore, Isuti Road', 'Lagos Mainland', 'Lagos'),
('Royal Prince Supermarket Berger', 'Lagos Mainland', 'Lagos'),
('Royal Prince Supermarket Gbagada', 'Lagos Mainland', 'Lagos'),
('Shoprite SR Ikeja City Mall 53443', 'Lagos Mainland', 'Lagos'),
('Simon''s Superstores, Agbara', 'Lagos Mainland', 'Lagos'),
('Smartiemart Mega Stores', 'Lagos Mainland', 'Lagos'),
('Spar Afprint Compound Surulere', 'Lagos Mainland', 'Lagos'),
('Spar Ilupeju, Mushin', 'Lagos Mainland', 'Lagos'),
('Spar Opebi Road, Ikeja', 'Lagos Mainland', 'Lagos'),
('SuperSaver Ajao Estate', 'Lagos Mainland', 'Lagos'),
('Supersaver Alapere', 'Lagos Mainland', 'Lagos'),
('Supersaver Central Warehouse', 'Lagos Mainland', 'Lagos'),
('Supersaver Ikosi', 'Lagos Mainland', 'Lagos'),
('Supersaver Shangishan Magodo', 'Lagos Mainland', 'Lagos'),
('Temple Hill Festac', 'Lagos Mainland', 'Lagos'),
('Temple hill Isolo', 'Lagos Mainland', 'Lagos'),
('The Label Store', 'Lagos Mainland', 'Lagos'),
('The Label Store, Kilo', 'Lagos Mainland', 'Lagos'),
('Udeme Supermarket, Ikeja', 'Lagos Mainland', 'Lagos'),
('Value Exchange Superstores, CMD', 'Lagos Mainland', 'Lagos'),
('Value Exchange Superstores, Magodo', 'Lagos Mainland', 'Lagos'),
('Valuemart Stores, Ekoro', 'Lagos Mainland', 'Lagos'),
('Veritas Value Village Ventures, Ogudu', 'Lagos Mainland', 'Lagos'),
('Victory City Supermarket, Anthony', 'Lagos Mainland', 'Lagos'),
('Westgate Cosmetics', 'Lagos Mainland', 'Lagos'),
('A.A Best', 'Trade Fair Complex', 'Lagos'),
('A.G Cosmetics', 'Trade Fair Complex', 'Lagos'),
('A.S Philips', 'Trade Fair Complex', 'Lagos'),
('Abuchi', 'Trade Fair Complex', 'Lagos'),
('Acalvien', 'Trade Fair Complex', 'Lagos'),
('Amaka Tic', 'Trade Fair Complex', 'Lagos'),
('Andrew (ayt Commercial Ent.)', 'Trade Fair Complex', 'Lagos'),
('Beauty Affairs', 'Trade Fair Complex', 'Lagos'),
('Ben Tradefair', 'Trade Fair Complex', 'Lagos'),
('Bismid', 'Trade Fair Complex', 'Lagos'),
('C Smart', 'Trade Fair Complex', 'Lagos'),
('C-Nature', 'Trade Fair Complex', 'Lagos'),
('chinedu', 'Trade Fair Complex', 'Lagos'),
('Chineye', 'Trade Fair Complex', 'Lagos'),
('Chioma (abf Opp.borno Plaza', 'Trade Fair Complex', 'Lagos'),
('chioma (Vizora)', 'Trade Fair Complex', 'Lagos'),
('Chogwu', 'Trade Fair Complex', 'Lagos'),
('Chybike', 'Trade Fair Complex', 'Lagos'),
('Cibson Investment', 'Trade Fair Complex', 'Lagos'),
('Contender', 'Trade Fair Complex', 'Lagos'),
('D Chuks Global', 'Trade Fair Complex', 'Lagos'),
('Destined', 'Trade Fair Complex', 'Lagos'),
('Divine Mercy', 'Trade Fair Complex', 'Lagos'),
('Ebuka T.f', 'Trade Fair Complex', 'Lagos'),
('Efe', 'Trade Fair Complex', 'Lagos'),
('Ejis Ocean', 'Trade Fair Complex', 'Lagos'),
('Ekene', 'Trade Fair Complex', 'Lagos'),
('Ella', 'Trade Fair Complex', 'Lagos'),
('Elsim', 'Trade Fair Complex', 'Lagos'),
('Emmanuel Ejemba', 'Trade Fair Complex', 'Lagos'),
('Fine Look', 'Trade Fair Complex', 'Lagos'),
('Genesis', 'Trade Fair Complex', 'Lagos'),
('Globus Relativity Stores Trade Fair', 'Trade Fair Complex', 'Lagos'),
('Jbo', 'Trade Fair Complex', 'Lagos'),
('Jude V Tradefair', 'Trade Fair Complex', 'Lagos'),
('jykesweb', 'Trade Fair Complex', 'Lagos'),
('Kanof', 'Trade Fair Complex', 'Lagos'),
('Kodis', 'Trade Fair Complex', 'Lagos'),
('Mac-visco Ltd', 'Trade Fair Complex', 'Lagos'),
('Madam Charles', 'Trade Fair Complex', 'Lagos'),
('Madam Chinenye', 'Trade Fair Complex', 'Lagos'),
('Madam Chinwe (ethel N Ella Beauty)', 'Trade Fair Complex', 'Lagos'),
('Madam Donella', 'Trade Fair Complex', 'Lagos'),
('Madam Grace', 'Trade Fair Complex', 'Lagos'),
('Madam Oluchi', 'Trade Fair Complex', 'Lagos'),
('Madam UC', 'Trade Fair Complex', 'Lagos'),
('Mark Choice', 'Trade Fair Complex', 'Lagos'),
('Mmiri Tradefair', 'Trade Fair Complex', 'Lagos'),
('N.K', 'Trade Fair Complex', 'Lagos'),
('Nomsky', 'Trade Fair Complex', 'Lagos'),
('Obinna Tradefair', 'Trade Fair Complex', 'Lagos'),
('oga chucks', 'Trade Fair Complex', 'Lagos'),
('Oga Emeka', 'Trade Fair Complex', 'Lagos'),
('Oga Frank', 'Trade Fair Complex', 'Lagos'),
('Oga O.C', 'Trade Fair Complex', 'Lagos'),
('Oga Onyeka', 'Trade Fair Complex', 'Lagos'),
('Oga Tony', 'Trade Fair Complex', 'Lagos'),
('Oga Vicky (Righteous Gate) Trade fair', 'Trade Fair Complex', 'Lagos'),
('Olivia', 'Trade Fair Complex', 'Lagos'),
('Oluchi', 'Trade Fair Complex', 'Lagos'),
('Onyeka Tradefair', 'Trade Fair Complex', 'Lagos'),
('oramore', 'Trade Fair Complex', 'Lagos'),
('Ozeh', 'Trade Fair Complex', 'Lagos'),
('P.tom', 'Trade Fair Complex', 'Lagos'),
('Penaforte Supermarket, Village Bus Stop', 'Trade Fair Complex', 'Lagos'),
('Solex Cosmetics (umeh)', 'Trade Fair Complex', 'Lagos'),
('Speedyon', 'Trade Fair Complex', 'Lagos'),
('Stand By', 'Trade Fair Complex', 'Lagos'),
('Stanley', 'Trade Fair Complex', 'Lagos'),
('Tagbo', 'Trade Fair Complex', 'Lagos'),
('Trade fair cash sales', 'Trade Fair Complex', 'Lagos'),
('Uk Daji', 'Trade Fair Complex', 'Lagos'),
('Valmac Ice Nig Ltd', 'Trade Fair Complex', 'Lagos'),
('VINOFF (Joy)', 'Trade Fair Complex', 'Lagos'),
('Wendy', 'Trade Fair Complex', 'Lagos'),
('Justrite Superstore Funaab, Ogun State', '', 'Ogun'),
('Sino Mart Superstore, Ota', '', 'Ogun'),
('Foodco Abeokuta', 'Abeokuta', 'Ogun'),
('Foodco Akinolugbade, Abeokuta', 'Abeokuta', 'Ogun'),
('Foodco Asero, Abeokuta', 'Abeokuta', 'Ogun'),
('Justrite Superstore Abeokuta', 'Abeokuta', 'Ogun'),
('Justrite Superstore Kemta, Ogun State', 'Abeokuta', 'Ogun'),
('Justrite Superstore Lafenwa, Ogun Satet', 'Abeokuta', 'Ogun'),
('Justrite Superstore Obantoko', 'Abeokuta', 'Ogun'),
('Shalom Mega Stores', 'Abeokuta', 'Ogun'),
('Ceci Mega Plaza, Akure', 'Akure', 'Ondo'),
('First Vigeo Supermarket, Akure', 'Akure', 'Ondo'),
('Nao Supermarket, Akure', 'Akure', 'Ondo'),
('O.u.k Supermarket, Akure', 'Akure', 'Ondo'),
('Ojajamore Supermarket, Akure', 'Akure', 'Ondo'),
('Olukem Supermarket, Akure', 'Akure', 'Ondo'),
('Shoprite SR Akure Mall 93144', 'Akure', 'Ondo'),
('Staleg Mall, Akure', 'Akure', 'Ondo'),
('Tush Mart Limited, Akure', 'Akure', 'Ondo'),
('Justrite Superstores Ilesha', 'Ilesha', 'Osun'),
('City Star Mart, Oshogbo', 'Osogbo', 'Osun'),
('Justrite Superstore Ile- Ife, Osun State', 'Osogbo', 'Osun'),
('Justrite Superstore Oshogbo', 'Osogbo', 'Osun'),
('Lead Supermarket Warehouse, Oshogbo', 'Osogbo', 'Osun'),
('Ojaja More Oshogbo', 'Osogbo', 'Osun'),
('Ojajamore Supermarket Ile-Ife', 'Osogbo', 'Osun'),
('Better Days', '', 'Others'),
('Bmc Cosmetics', '', 'Others'),
('Bright Links Cosmetics Hub', '', 'Others'),
('Ceebeco', '', 'Others'),
('Chuppet', '', 'Others'),
('Coach Supermarket', '', 'Others'),
('Don Bishop (onyeka Hillary)', '', 'Others'),
('James Peter', '', 'Others'),
('Judith', '', 'Others'),
('Katta Supermarket, AIT Branch', '', 'Others'),
('Legend Supermarket (opposite House On The Rock)', '', 'Others'),
('Madina Lifestyle & Supermarket, Somolu', '', 'Others'),
('Maldora supermarket , Ifako', '', 'Others'),
('Market Square Delta Mall', '', 'Others'),
('Mary Anu', '', 'Others'),
('Obireal', '', 'Others'),
('Obum Tradefair', '', 'Others'),
('Patcargo (nonso)', '', 'Others'),
('Penny Express Ago', '', 'Others'),
('Rabbi', '', 'Others'),
('Shoprite SR Abia Mall 35300', '', 'Others'),
('Shoprite Sr Adeniran 57617', '', 'Others'),
('Shoprite Sr Circle Mall 64808', '', 'Others'),
('Shoprite Sr Cocoa Mall 37726', '', 'Others'),
('Shoprite SR Delta Mall 64785', '', 'Others'),
('Shoprite SR Festival Mall 64777', '', 'Others'),
('shoprite SR GRAND TOWER', '', 'Others'),
('Shoprite Sr Jabi Lake 64793', '', 'Others'),
('Shoprite SR Kwara Mall 56221', '', 'Others'),
('Shoprite Sr Otta Gateway 83311', '', 'Others'),
('Shoprite SR Park Lane 37734', '', 'Others'),
('Shoprite Sr Silverbird 38073', '', 'Others'),
('Shoprite Sr the Palms 44917', '', 'Others'),
('Spar Adeola Odeku, VI', '', 'Others'),
('The Brands Superstores, Pedro', '', 'Others'),
('Twins Faja Supermarket, Ijanikin', '', 'Others'),
('Twins Faja Supermarket, Ipaye B/S', '', 'Others'),
('U B A Supermarket Awoyaya Bus Stop', '', 'Others'),
('Unique Superstore, Ede', '', 'Others'),
('Value Exchange Superstores, Arepo', '', 'Others'),
('Ace Mall Bodija, Ibadan', 'Ibadan', 'Oyo'),
('Brent Mall Warehouse, Ibadan', 'Ibadan', 'Oyo'),
('Buy and Save Bodija, Ibadan', 'Ibadan', 'Oyo'),
('Danax Cosmetics, Ibadan', 'Ibadan', 'Oyo'),
('Finrel Warehouse, Ibadan', 'Ibadan', 'Oyo'),
('Foodco Ibadan', 'Ibadan', 'Oyo'),
('Foodco Jericho Warehouse, Ibadan', 'Ibadan', 'Oyo'),
('Foodco Monatan Warehouse, Ibadan', 'Ibadan', 'Oyo'),
('Foodco Ologuneru Warehouse, Ibadan', 'Ibadan', 'Oyo'),
('Foodco Ring Road Warehouse, Ibadan', 'Ibadan', 'Oyo'),
('Foodies Supermarket Jericho, Ibadan', 'Ibadan', 'Oyo'),
('Jara Oyo', 'Ibadan', 'Oyo'),
('Justrite Supermarket Eleyele, Ibadan', 'Ibadan', 'Oyo'),
('Justrite Superstore Akobo, Ibadan', 'Ibadan', 'Oyo'),
('Justrite Superstore Ring Road, Ibadan', 'Ibadan', 'Oyo'),
('Market Square Gbagi, Ibadan', 'Ibadan', 'Oyo'),
('More Mart Alakia, Ibadan', 'Ibadan', 'Oyo'),
('More Mart Olorunsogo, Ibadan', 'Ibadan', 'Oyo'),
('More Mart Olunde, Ibadan', 'Ibadan', 'Oyo'),
('Mosh Pharmacy and Supermarket Bodija, Ibadan', 'Ibadan', 'Oyo'),
('SFY Superstores, Ibadan', 'Ibadan', 'Oyo'),
('Shokem Supermarket Ibadan, UI Branch', 'Ibadan', 'Oyo'),
('Shokem Supermarket, Ibadan', 'Ibadan', 'Oyo'),
('Shoprite Sr Ibadan Mall 56255', 'Ibadan', 'Oyo'),
('Staleg Mall, Ibadan', 'Ibadan', 'Oyo'),
('Sunrise Supermarket, Ibadan', 'Ibadan', 'Oyo'),
('Vanguard Pharmacy, Akobo', 'Ibadan', 'Oyo'),
('Amechi PH', 'Port Harcourt', 'Rivers'),
('Buyplus Mall D Line, PH', 'Port Harcourt', 'Rivers'),
('Emilo Super Market', 'Port Harcourt', 'Rivers'),
('Essence Needz Eneka PH', 'Port Harcourt', 'Rivers'),
('Essence Needz PH', 'Port Harcourt', 'Rivers'),
('Everyday Supermarket Choba Ph E6', 'Port Harcourt', 'Rivers'),
('Everyday Supermarket Gra Ph E2', 'Port Harcourt', 'Rivers'),
('Everyday Supermarket Mgbuoba Ph E9', 'Port Harcourt', 'Rivers'),
('Everyday Supermarket Peter Odili', 'Port Harcourt', 'Rivers'),
('Everyday Supermarket Rumuibekwe E3 Ph', 'Port Harcourt', 'Rivers'),
('Everyday Supermarket Rumuola E1 Ph', 'Port Harcourt', 'Rivers'),
('Exotica Ph', 'Port Harcourt', 'Rivers'),
('Hepzibah Supermarket, Eket', 'Port Harcourt', 'Rivers'),
('HyperCity Ogunabali Port Harcourt', 'Port Harcourt', 'Rivers'),
('Hypercity Retail Ltd Ikoku, PH', 'Port Harcourt', 'Rivers'),
('HyperCity Retail ltd Tombia Road New GRA PH', 'Port Harcourt', 'Rivers'),
('Hypercity Retail Ltd, Trans-Amadi Rd, Port Harcourt', 'Port Harcourt', 'Rivers'),
('Market Square Ada George PH', 'Port Harcourt', 'Rivers'),
('Market Square Agip Road, PH', 'Port Harcourt', 'Rivers'),
('Market Square Choba', 'Port Harcourt', 'Rivers'),
('Market Square Eket', 'Port Harcourt', 'Rivers'),
('Market Square Elelenwo Ph', 'Port Harcourt', 'Rivers'),
('Market Square Eleme, PH', 'Port Harcourt', 'Rivers'),
('Market Square GRA Phase 3 PH', 'Port Harcourt', 'Rivers'),
('Market Square Iwofe Road', 'Port Harcourt', 'Rivers'),
('Market square Mile 3, PH', 'Port Harcourt', 'Rivers'),
('Market Square Nzimiro, Port Harcourt', 'Port Harcourt', 'Rivers'),
('Market square Okporo Rumudara Ph', 'Port Harcourt', 'Rivers'),
('Market Square Onne PH', 'Port Harcourt', 'Rivers'),
('Market Square Peter Odili PH', 'Port Harcourt', 'Rivers'),
('Market Square Rukpokwu AIrport RD PH', 'Port Harcourt', 'Rivers'),
('Market Square Rumuibekwe PH', 'Port Harcourt', 'Rivers'),
('Next Cash & Carry PH', 'Port Harcourt', 'Rivers'),
('Shoprite SR Garden City Mall PH 79380', 'Port Harcourt', 'Rivers'),
('Spar Port Harcourt', 'Port Harcourt', 'Rivers'),
('Super City Supermarket, PH', 'Port Harcourt', 'Rivers'),
('The Prince Mega Cosmetics', 'Port Harcourt', 'Rivers'),
('Welcome U Supermarket', 'Port Harcourt', 'Rivers'),
('Wide Choice Ada George', 'Port Harcourt', 'Rivers'),
('Wide Choice Choba PH', 'Port Harcourt', 'Rivers'),
('Wide Choice Iwofe', 'Port Harcourt', 'Rivers');

SELECT CONCAT('OK — stores loaded: ', COUNT(*)) AS result FROM stores;
SELECT state, COUNT(*) AS stores FROM stores GROUP BY state ORDER BY stores DESC;